# A linear regression plugin for Elasticsearch

image:https://travis-ci.org/scaleborn/elasticsearch-linear-regression.svg?branch=master["Build Status", link="https://travis-ci.org/scaleborn/elasticsearch-linear-regression"]

Linear regression is one of the most well known algorithms in machine learning. It defines a predictive model for the value
of a response variable based on a training data set of explanatory variables when the relationship between the variables can be
described with a linear model. This technique belongs to the supervised learning algorithms in machine learning.

The core idea behind this plugin is to utilize the index data in Elasticsearch during search 
as a linear regression model in order to expose information like

* prediction of a value for the target variable,
* anomaly detection,
* measuring the accuracy or rather predictiveness of the model
* and much more.


## Aggregations

=== Linear Regression Stats

The `linreg_stats` aggregation is a numeric aggregation that computes a linear regression
model over a set of document fields standing for the response and the explanatory variables.

[horizontal]
`rss`:: Residual sum of squares as a measure of the discrepancy between the data and the estimated model.
        The lower the `rss` number, the smaller the error of the prediction, and the better the model.
`mse`:: Mean squared error or rather `rss` divided by the number of documents consumed for model estimation.
`coefficients`:: Slope coefficients image:http://latex.codecogs.com/gif.latex?\theta_1,%20\theta_2,%20\theta_3,%20...,%20\theta_C
                 of the linear function estimated regarding least-squares regression.
`intercept`:: Intercept coefficient image:http://latex.codecogs.com/gif.latex?\theta_0
                 of the linear function estimated regarding least-squares regression.


## Installation

### Elasticsearch 5.x
For installing this plugin please choose first the proper version under the compatible
matrix which matches your Elasticsearch version and use the download link for the following command.

[source]
----
./bin/elasticsearch-plugin install https://github.com/scaleborn/elasticsearch-linear-regression/releases/download/5.3.0.1/elasticsearch-linear-regression-5.3.0.1.zip
----
The plugin will be installed under the name "linear-regression".
Do not forget to restart the node after installing.

.Compatibility matrix
[frame="all"]
|===
| Plugin version | Elasticsearch version | Release date
| https://github.com/scaleborn/elasticsearch-linear-regression/releases/download/5.3.0.1/elasticsearch-linear-regression-5.3.0.1.zip[5.3.0.1]        | 5.3.0 | Jun  1, 2017
|===
