# A multiple linear regression plugin for Elasticsearch

image:https://travis-ci.org/scaleborn/elasticsearch-linear-regression.svg?branch=master["Build Status", link="https://travis-ci.org/scaleborn/elasticsearch-linear-regression"]

Linear regression model has been a mainstay of statistics and machine learning
in the past decades and remains one of the most important tools in context of supervised learning algorithms.
It's a powerful technique for prediction of the value of a dependent variable `y` (called response variable) given the values of another independent
variables `x = (x~1~, x~2~,...,x~C~)` (called explanatory variables) based on a training data set. Prediction of the response variable with respect to the input values
 for the explanatory variables is described by the linear hypothesis function ``h(x)`` with

image:http://latex.codecogs.com/gif.latex?h(x)%20=%20\theta_{0}%20+%20\sum_{j=1}^C%20\theta_{j}%20x_{j}[]

This plugin enhances Elasticsearch's query engine by two new aggregations, which utilize the index data during search
for estimating a linear regression model in order to expose information like prediction of a value for the target variable,
anomaly detection and measuring the accuracy or rather predictiveness of the model.
Estimation is performed regarding the https://en.wikipedia.org/wiki/Ordinary_least_squares[OLS]
(ordinary least-squares) approach over the search result set.


## Aggregations
Both aggregations are numeric aggregations that estimate the linear regression coefficients
image:http://latex.codecogs.com/gif.latex?\theta_0,%20\theta_1,%20\theta_2,.%20.%20.,%20\theta_C%20[]
based on document results of a search query. Each search result
document is handled as an observation and the numerical fields as variables (explanatory and response)
for the linear model.


=== Linear Regression Stats

The `linreg_stats` aggregation computes statistics for the estimated linear regression model.

[horizontal]
`rss`:: Residual sum of squares as a measure of the discrepancy between the data and the estimated model.
        The lower the `rss` number, the smaller the error of the prediction, and the better the model.
`mse`:: Mean squared error or rather `rss` divided by the number of documents consumed for model estimation.
`coefficients`:: Slope coefficients
  image:http://latex.codecogs.com/gif.latex?\theta_1,%20\theta_2,%20\theta_3,.%20.%20.,%20\theta_C%20[]
    of the linear linear hypothesis function ``h(x)``.
`intercept`:: Intercept coefficient image:http://latex.codecogs.com/gif.latex?\theta_0%20[]
                 of the linear hypothesis function ``h(x)``.


## Installation

### Elasticsearch 5.x
For installing this plugin please choose first the proper version under the compatible
matrix which matches your Elasticsearch version and use the download link for the following command.

[source]
----
./bin/elasticsearch-plugin install https://github.com/scaleborn/elasticsearch-linear-regression/releases/download/5.3.0.1/elasticsearch-linear-regression-5.3.0.1.zip
----
The plugin will be installed under the name "linear-regression".
Do not forget to restart the node after installing.

.Compatibility matrix
[frame="all"]
|===
| Plugin version | Elasticsearch version | Release date
| https://github.com/scaleborn/elasticsearch-linear-regression/releases/download/5.3.0.1/elasticsearch-linear-regression-5.3.0.1.zip[5.3.0.1]        | 5.3.0 | Jun  1, 2017
|===
